/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "GitHubLikeMCP" | "Chat";
  }
  interface Env {
    AI: Ai;
    LOADER: WorkerLoader;
    GitHubLikeMCP: DurableObjectNamespace<import("./src/server").GitHubLikeMCP>;
    Chat: DurableObjectNamespace<import("./src/server").Chat>;
  }
}
interface Env extends Cloudflare.Env {}
