/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: b957c8d0279c84ba3e3b7cc9b39df0e6)
interface __BaseEnv_Env {
  DeployChurnAgent: DurableObjectNamespace<
    import("./src/server").DeployChurnAgent
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "DeployChurnAgent";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
