/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false env.d.ts` (hash: d756c15aedacd07aba3c156892370ede)
interface __BaseEnv_Env {
  AI: Ai;
  DeployChurnAgent: DurableObjectNamespace<
    import("./src/server").DeployChurnAgent
  >;
  DeployChurnSubAgentChild: DurableObjectNamespace<
    import("./src/server").DeployChurnSubAgentChild
  >;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "DeployChurnAgent" | "DeployChurnSubAgentChild";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
