/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: fae17daf2463a624f0f7d49c746f75f4)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ResumableStreamingChat";
  }
  interface Env {
    ResumableStreamingChat: DurableObjectNamespace<
      import("./src/server").ResumableStreamingChat
    >;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
