/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: ceb47556f45c7e915398d74f3b5267bb)
interface __BaseEnv_Env {
  Parent: DurableObjectNamespace<import("./src/index").Parent>;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "Parent" | "Child";
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
