/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 948361215356b60c802641db6b78a054)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces:
      | "StateAgent"
      | "CallableAgent"
      | "StreamingAgent"
      | "ScheduleAgent"
      | "SqlAgent"
      | "ConnectionsAgent"
      | "RoutingAgent"
      | "ChatAgent"
      | "SupervisorAgent"
      | "ChildAgent"
      | "LobbyAgent"
      | "RoomAgent"
      | "BasicWorkflowAgent"
      | "ApprovalAgent"
      | "ReceiveEmailAgent"
      | "SecureEmailAgent";
  }
  interface Env {
    EMAIL_SECRET: "demo-secret-change-in-production";
    OPENAI_API_KEY: string;
    StateAgent: DurableObjectNamespace<import("./src/server").StateAgent>;
    CallableAgent: DurableObjectNamespace<import("./src/server").CallableAgent>;
    StreamingAgent: DurableObjectNamespace<
      import("./src/server").StreamingAgent
    >;
    ScheduleAgent: DurableObjectNamespace<import("./src/server").ScheduleAgent>;
    SqlAgent: DurableObjectNamespace<import("./src/server").SqlAgent>;
    ConnectionsAgent: DurableObjectNamespace<
      import("./src/server").ConnectionsAgent
    >;
    RoutingAgent: DurableObjectNamespace<import("./src/server").RoutingAgent>;
    ChatAgent: DurableObjectNamespace<import("./src/server").ChatAgent>;
    SupervisorAgent: DurableObjectNamespace<
      import("./src/server").SupervisorAgent
    >;
    ChildAgent: DurableObjectNamespace<import("./src/server").ChildAgent>;
    LobbyAgent: DurableObjectNamespace<import("./src/server").LobbyAgent>;
    RoomAgent: DurableObjectNamespace<import("./src/server").RoomAgent>;
    BasicWorkflowAgent: DurableObjectNamespace<
      import("./src/server").BasicWorkflowAgent
    >;
    ApprovalAgent: DurableObjectNamespace<import("./src/server").ApprovalAgent>;
    ReceiveEmailAgent: DurableObjectNamespace<
      import("./src/server").ReceiveEmailAgent
    >;
    SecureEmailAgent: DurableObjectNamespace<
      import("./src/server").SecureEmailAgent
    >;
    ProcessingWorkflow: Workflow<
      Parameters<import("./src/server").ProcessingWorkflow["run"]>[0]["payload"]
    >;
    ApprovalWorkflow: Workflow<
      Parameters<import("./src/server").ApprovalWorkflow["run"]>[0]["payload"]
    >;
  }
}
interface Env extends Cloudflare.Env {}
