/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 1450a1824df1148c0455597dc0515bfb)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "PayMCP" | "PayAgent";
  }
  interface Env {
    MCP_OBJECT: DurableObjectNamespace<import("./src/server").PayMCP>;
    PAY_AGENT: DurableObjectNamespace<import("./src/server").PayAgent>;
  }
}
interface Env extends Cloudflare.Env {}
