/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: 6f0d6a825441d484ec34a71abd1158d9)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/index");
    durableNamespaces: "McpWidgetAgent" | "ChessGame";
  }
  interface Env {
    MCP_OBJECT: DurableObjectNamespace<import("./src/index").McpWidgetAgent>;
    CHESS: DurableObjectNamespace<import("./src/index").ChessGame>;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
