/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 7a275c5f52e8dc3e65e65cbae6cd72ac)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "WorkspaceChatAgent";
  }
  interface Env {
    AI: Ai;
    WorkspaceChatAgent: DurableObjectNamespace<
      import("./src/server").WorkspaceChatAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
